### ISSUE TITLE
Niepoprawne linki na stronie głównej

### ISSUE THREAD

**Issue by Roen00** [f4wst53dd/abc#2]
Linki na stronie głównej https://github.com/f4wst53dd/abc np: https://github.com/f4wst53dd/wstep/o_poradniku.md

przekierowują na 404, chyba wszystkie linki w spisie treści sa popsute :(

**Comment by f4wst53dd** [comment]
@Roen00 Umieściłem projekt na [GitBooks](https://f4wst53dd.gitbooks.io/abc/content/) zatem teraz nawigacja nie powinna sprawiać problemów (spis treści jest po lewej stronie).
